-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.30 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for db_tokomainan
CREATE DATABASE IF NOT EXISTS `db_tokomainan` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `db_tokomainan`;

-- Dumping structure for table db_tokomainan.admin
CREATE TABLE IF NOT EXISTS `admin` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL DEFAULT '',
  `password` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table db_tokomainan.admin: ~1 rows (approximately)
INSERT INTO `admin` (`id`, `username`, `password`) VALUES
	(1, 'admin', '123');

-- Dumping structure for table db_tokomainan.produk
CREATE TABLE IF NOT EXISTS `produk` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nama_produk` varchar(100) DEFAULT NULL,
  `kategori` varchar(50) DEFAULT NULL,
  `umur` varchar(50) DEFAULT NULL,
  `harga` bigint DEFAULT NULL,
  `stok` int DEFAULT NULL,
  `foto` varchar(100) DEFAULT NULL,
  `deskripsi` text,
  `rating` decimal(3,1) DEFAULT '5.0',
  `terjual` int DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=110 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table db_tokomainan.produk: ~80 rows (approximately)
INSERT INTO `produk` (`id`, `nama_produk`, `kategori`, `umur`, `harga`, `stok`, `foto`, `deskripsi`, `rating`, `terjual`) VALUES
	(1, 'Mofusand Shark', 'Boneka', NULL, 150000, 3, 'mofusand_shark.jpg', 'Mofusand shark plush keychain ini punya look yang gemesin banget dengan kucing oranye yang pakai kostum hiu abu-abu berbahan plush super lembut dan sudah dilengkapi rantai gantungan kunci perak di atasnya. detail wajahnya yang polos dengan aksen tapak kaki pink yang manis bikin gantungan ini cocok banget buat hiasan tas atau kunci kamu supaya makin estetik dan unik.', 4.8, 12),
	(2, 'Mofusand Shark Flower', 'Boneka', '12+ Tahun', 200000, 10, '06012026194259mofusand shark flower.jpg', 'Mofusand shark flower edition ini bener-bener definisi gemas maksimal, karena kucing oranye imut ini pakai kostum hiu abu-abu yang teksturnya terlihat lembut dan dwi-fungsi sebagai dekorasi yang estetik. sambil memeluk buket bunga pink cantik dengan pita ungu, figurin ini memancarkan aura manis yang cocok banget buat dijadikan hadiah penyemangat atau sekadar pemanis meja kerja kamu. detail wajah kucing yang sayu dan sirip hiu yang unik bikin koleksi satu ini terasa sangat spesial, jadi jangan sampai lewatkan kesempatan buat adopsi si anabul berkostum hiu ini ya!', 4.7, 18),
	(3, 'Mofusand Green Dino', 'Boneka', NULL, 250000, 8, 'mofusand_green_dino.jpg', 'Mofusand green dino hadir dengan kostum dinosaurus hijau yang empuk dan punya detail gerigi putih khas dino di bagian kepalanya yang bikin si kucing kelihatan makin playful. boneka ini punya tekstur yang nyaman dipeluk dengan ekspresi wajah yang menenangkan, pas banget buat jadi koleksi pajangan di kamar atau kado spesial buat pecinta anabul yang suka gaya unik.', 4.8, 20),
	(13, 'Robot Bumblebee', 'Action Figure', NULL, 1000000, 10, 'Robot 3.jpeg', 'Aksi seru tak terbatas menanti dengan mainan robot transformator 2-in-1 yang luar biasa ini! Dengan mudah beralih dari mode Robot pejuang yang kuat ke mode Mobil Sport yang ramping, mainan ini akan memicu imajinasi dan kreativitas anak Anda. Desain yang sangat mirip dengan karakter ikonik Bumblebee, robot ini siap untuk pertarungan dan balapan!', 0.0, 0),
	(14, 'Robot Optimus Prime', 'Action Figure', NULL, 1500000, 13, 'Robot 4.jpeg', 'Rasakan kekuatan pemimpin Autobots dengan mainan robot transformasi premium ini! Model ini menghadirkan detail yang sangat tinggi dan menakjubkan dari karakter ikonik, siap untuk bertransformasi dari truk semi-trailer yang perkasa menjadi robot pejuang yang heroik.', 0.0, 0),
	(15, 'Action Figure Batman', 'Action Figure', NULL, 200000, 20, 'Robot 5.jpeg', 'Figur aksi ini menampilkan karakter ikonik Batman dari alam semesta DC Comics, dengan desain yang kokoh dan siap untuk dimainkan atau dipajang.', 0.0, 0),
	(16, 'Action Figure Iron Man', 'Action Figure', NULL, 500000, 30, 'Robot 6.jpeg', 'Ini adalah figur aksi karakter Iron Man dari Marvel Comics, yang menampilkan gaya desain yang khas dan spesifik.', 0.0, 0),
	(17, 'Action Figure Roronoa Zoro', 'Action Figure', NULL, 925000, 20, 'Robot 8.jpeg', 'Ini adalah figur koleksi karakter Roronoa Zoro dari One Piece, namun dalam setelan kostum yang sangat unik dan bukan kostum bajak laut tradisionalnya. Kostum ini mengarah pada tema fiksi ilmiah atau gaya modern/futuristik.', 0.0, 0),
	(18, 'Action Figure Portgas D. Ace', 'Action Figure', NULL, 930000, 13, 'Robot 9.jpeg', 'Ini adalah figur koleksi karakter Portgas D. Ace dari One Piece, saudara angkat Monkey D. Luffy dan komandan Divisi Kedua Bajak Laut Shirohige.', 0.0, 0),
	(20, 'Action Figure Monkey D.Luffy', 'Action Figure', NULL, 1000000, 20, 'Robot 10.1.jpeg', 'Figur koleksi ini menampilkan karakter utama dari One Piece, Monkey D. Luffy, yang berpose ceria dengan senyum lebar, satu tangan memegang topi jerami ikoniknya di atas kepala. Ia mengenakan kemeja/jaket lengan panjang berwarna merah terang yang dibiarkan terbuka, memamerkan detail otot perut yang terpahat, dan dipadukan dengan celana pendek longgar berwarna kuning/oranye dengan tepian berbulu putih. Ikat pinggang/selempang berwarna ungu melingkari pinggangnya, dan ia beralas kaki dengan sandal sederhana berwarna cokelat. Figur ini memiliki detail fisik yang presisi dan menampilkan postur dinamis, khas figur pajangan berkualitas tinggi.', 0.0, 0),
	(21, 'Action Figure God D.Usopp', 'Action Figure', NULL, 1000000, 15, 'Robot 10.jpeg', 'Figur koleksi ini menampilkan karakter Usopp dari One Piece, sang penembak jitu Bajak Laut Topi Jerami, dalam postur berani dengan tangan terlipat di dada dan ekspresi wajah yang tegas, menonjolkan hidungnya yang panjang. Ia berdiri di atas alas bundar hitam dan mengenakan pakaian ala koboi/petualang yang didominasi warna cokelat dan oranye tua, termasuk topi tricorn khasnya. Kostumnya terdiri dari kemeja/jaket yang dipadukan dengan celana panjang balon (baggy) yang dimasukkan ke sepatu bot, serta dilengkapi dengan sarung senjata dan pisau di pinggangnya, dan selempang panjang yang tersampir di bahunya, memberikan kesan petualang yang siap beraksi.', 0.0, 0),
	(22, 'Action Figure Sabo', 'Action Figure', NULL, 1000000, 13, 'Robot 11.jpeg', 'Figur koleksi ini menampilkan karakter Sabo, Kepala Staf Pasukan Revolusioner dan saudara angkat Monkey D. Luffy dan Portgas D. Ace, dalam penampilan klasiknya yang formal namun siap tempur. Sabo berpose tegak dengan tangan kanannya sedikit menyentuh topi tingginya yang berwarna hitam, di mana terdapat kacamata pelindung (goggle) berwarna oranye/kuning melingkar. Ia mengenakan mantel panjang berwarna hitam gelap dengan lapisan dalam berwarna biru cerah, yang menutupi setelan formal berwarna biru muda dengan kancing emas dan cravat (dasi leher) besar berwarna putih. Di tangan kirinya, ia memegang pipa logam panjang yang merupakan senjata khasnya, memberikan kesan elegan sekaligus kuat, menjadikannya figur pajangan yang sangat detail.', 0.0, 0),
	(26, 'Boneka Labubu', 'Boneka', NULL, 200000, 12, '06012026194059labubu.jpg', 'Pop mart labubu time to chill ini tampil stylish banget pakai kemeja salur biru dan celana jeans yang bikin look-nya makin gemesin buat dikoleksi. dengan ciri khas mata pink bentuk hati dan bulu cream yang super lembut, art toy ini punya detail premium dari ujung telinga sampai sepatu sneakers-nya yang rapi banget. pas banget buat kamu jadiin pajangan estetik di meja atau kado spesial buat orang tersayang, jadi yuk buruan adopsi labubu keren ini sebelum kehabisan stok! ', 0.0, 0),
	(27, 'Tung Tung Sahur', 'Boneka', NULL, 80000, 14, 'Boneka 4.jpeg', 'Boneka ini merupakan representasi fisik dari karakter meme viral Tung Tung Sahur, yang populer di media sosial, terutama TikTok, dan dikenal sebagai bagian dari tren "Anomali" atau "Italian Brainrot" yang berasal dari Indonesia.', 0.0, 0),
	(28, 'Boneka Jerapah', 'Boneka', NULL, 85000, 20, 'Boneka 3.jpeg', 'Boneka Jerapah, terbuat dari bahan yang lembut, cocok untuk menjadi boneka anak anak', 0.0, 0),
	(29, 'Boneka Ayam', 'Boneka', NULL, 65000, 25, 'Boneka 8.jpeg', 'Boneka ini terbuat dari bahan yang lembut, dibuat berbentuk ayam, sebgai mainan untuk anak anak', 0.0, 0),
	(30, 'Boneka Macan Tutul', 'Boneka', NULL, 85000, 15, 'Boneka 7.jpeg', 'Boneka plush berbentuk hewan dengan corak bintik-bintik cokelat gelap pada dasar putih/krem. Boneka ini memiliki moncong dan hidung yang besar, dan melingkari lehernya dengan syal berwarna cokelat kemerahan.', 0.0, 0),
	(31, 'Teddy Bear', 'Boneka', NULL, 150000, 13, 'Boneka 6. Teddy Bear.jpeg', 'Boneka plush klasik yang sangat besar, terbuat dari bulu tebal berwarna cokelat muda (tan), dihiasi pita dasi kupu-kupu kotak-kotak hitam putih di lehernya.', 0.0, 0),
	(32, 'Boneka Puppy', 'Boneka', NULL, 90000, 16, 'Boneka 2.jpeg', 'Boneka plush yang menyerupai anak kucing (kitten) berwarna abu-abu muda yang seragam dan berbulu tebal. Ciri utamanya adalah mata besar berwarna kuning-cokelat keemasan yang sangat ekspresif.', 0.0, 0),
	(33, 'Boneka Huggy Wuggy', 'Boneka', NULL, 125000, 18, 'Boneka 5.jpeg', 'Boneka plush yang didominasi warna pink cerah, terbuat dari bahan berbulu tebal (fluffy). Boneka ini memiliki dua mata besar, mulut terbuka lebar dengan deretan gigi taring yang tajam, dan dihiasi pita biru di lehernya. Tangan dan kakinya berwarna kuning terang. Boneka ini adalah karakter dari Poppy Playtime.', 0.0, 0),
	(35, 'Balok Susun Gerobak Kayu', 'Edukasi', NULL, 200000, 52, 'download.jpeg', 'Mainan ini adalah mainan edukasi klasik yang dikenal sebagai set balok susun (building blocks) yang ditempatkan dalam wadah khusus.', 0.0, 0),
	(36, 'Shape Sorter', 'Edukasi', NULL, 150000, 20, 'images (1).jpeg', 'Mainan ini adalah mainan edukasi klasik yang dikenal sebagai penyortir bentuk (shape sorter), ditujukan untuk anak usia dini. Wadahnya berbentuk kubus terbuat dari kayu alami yang memiliki tutup berengsel. Di bagian tutup dan sisi-sisi kotak terdapat lubang-lubang yang dipotong dalam berbagai bentuk geometris (seperti persegi, segitiga, lingkaran, dan pentagon). Mainan ini dilengkapi dengan balok-balok kayu berwarna cerah (merah, kuning, biru, hijau, oranye) dengan bentuk yang sesuai. Fungsi utama mainan ini adalah mengembangkan kemampuan anak dalam mengenali bentuk, mencocokkan, memecahkan masalah, dan mengasah keterampilan motorik halus dengan memasukkan balok ke lubang yang tepat.', 0.0, 0),
	(39, 'Puzzle Anak Dalam Kotak Timah', 'Edukasi', NULL, 50000, 15, 'images (4).jpeg', 'Mainan ini membantu mengembangkan keterampilan mencocokkan, memecahkan masalah, pengenalan bentuk, dan keterampilan motorik halus.', 0.0, 0),
	(40, 'Rubik Cube Klasik ', 'Edukasi', NULL, 30000, 21, 'images (5).jpeg', 'Mainan ini adalah teka-teki kombinasi tiga dimensi yang ikonik. Mainan ini menguji kemampuan spasial, memecahkan masalah, dan keterampilan logika.', 0.0, 0),
	(41, 'Mainan Pukul Palu', 'Edukasi', NULL, 20000, 21, 'images (6).jpeg', 'Mainan ini adalah mainan interaktif yang dirancang untuk melatih motoMainan ini bertujuan untuk melatih koordinasi mata dan tangan, keterampilan motorik kasar, dan konsentrasi anak-anak saat mereka mencoba memukul bola yang menyala atau muncul.rik kasar dan kecepatan reaksi anak. ', 5.0, 0),
	(43, 'Balok Susun Plastik', 'Edukasi', NULL, 45000, 13, 'images.jpeg', 'Mainan ini adalah set balok edukasi yang dirancang untuk mengombinasikan permainan membangun dengan pembelajaran matematika dasar. Balok-balok ini berbentuk kubus kecil yang terbuat dari plastik dan memiliki konektor yang memungkinkan mereka saling mengunci (interlocking) di setiap sisinya, memungkinkan anak-anak menyusunnya menjadi berbagai struktur 3D. Balok-balok tersebut hadir dalam warna yang sangat cerah (merah, biru, kuning, hijau, pink), dan setiap sisi balok memiliki angka (seperti 1, 2, 3, 4, 5) atau simbol operasi matematika (+, -, x, /) yang diukir atau dicetak. Fungsi mainan ini adalah untuk mengembangkan keterampilan motorik halus, kemampuan spasial, serta memperkenalkan konsep angka dan berhitung melalui permainan.', 0.0, 0),
	(45, 'Mobil Remote Control Wild Twister', 'Kendaraan', NULL, 150000, 12, 'Mobil 2.jpeg', 'Mainan ini adalah mobil kendali jarak jauh (RC Car) khusus yang dirancang untuk aksi stunt dan gerakan akrobatik. Mobil ini memiliki desain yang ekstrem dengan empat roda besar berwarna hijau neon yang bergerigi, memberikan traksi superior dan kemampuan off-road yang baik. Chassisnya didesain agar dapat membalikkan diri dan berputar (tumbling atau twister) 360 derajat tanpa henti. Mobil ini dikontrol menggunakan remot kontrol berbentuk gamepad berwarna hitam dengan aksen kuning neon, dan bodi mobil didominasi warna hijau neon dan hitam. Fungsi utamanya adalah memberikan pengalaman bermain yang penuh aksi stunt dan ketangkasan di berbagai permukaan.', 0.0, 0),
	(47, 'Tamiya Mini 4WD', 'Kendaraan', NULL, 650000, 4, 'Mobil 4.jpeg', 'Mobil balap miniatur berskala kecil, dikenal sebagai Mini 4WD (empat roda penggerak mini). Mobil ini didorong oleh motor listrik dan baterai internal, tanpa remot kontrol. Mainan ini adalah mobil balap miniatur tanpa kendali jarak jauh, dirancang untuk balapan di trek khusus', 0.0, 0),
	(48, 'Adventure Hammer Happy truck', 'Kendaraan', NULL, 86000, 18, 'download (3).jpeg', 'Mobil Hammer siap menemani si kecil untuk jelajah disetiap sudut dunia luar. Ukurannya yang besar dan lajunya yang kencang dapat menambah keseruan dan keceriaan si kecil. ', 0.0, 0),
	(49, 'Mobil Mainan Anak Animal Vehicle', 'Kendaraan', NULL, 200000, 25, 'download (2).jpeg', 'Mobil mainan anak-anak dengan desain yang menggemaskan dan kokoh. Mobil ini didominasi warna merah cerah.', 0.0, 0),
	(50, 'New Monster 1/20 RC Racing Vehicle ', 'Kendaraan', NULL, 237000, 20, 'download (4).jpeg', 'Mobil Balap Monster Kids Baru Skala 1/20 Simulasi Mobil Off Road 30m Super Cepat Model Mobil Mainan Murah dengan Lampu Depan Keren', 0.0, 0),
	(51, 'Xylophone pelangi mini', 'Edukasi', NULL, 35000, 20, 'Edukasi 2.jpeg', 'Xylophone pelangi mini ini adalah mainan musik edukatif yang sempurna untuk memperkenalkan anak-anak pada dunia melodi dan warna. Alat musik perkusi ini terdiri dari delapan bilah nada berwarna cerah seperti pelangi yang dipasang pada bingkai kayu yang kokoh, menghasilkan nada dasar yang jelas saat dipukul. Dilengkapi dengan dua stik pemukul kayu berujung bola merah yang aman dan mudah digenggam, mainan ini tidak hanya merangsang kreativitas dan apresiasi musik anak, tetapi juga membantu mengembangkan keterampilan motorik halus dan koordinasi mata-tangan mereka.', 0.0, 0),
	(52, 'Mainan Kayu Pencocokan Warna dan Pola', 'Edukasi', NULL, 50000, 12, 'Edukasi 3.jpeg', 'Produk ini adalah mainan edukasi berbahan dasar kayu yang dikenal sebagai Permainan Mencocokkan Warna dan Pola (Color and Pattern Matching Game) atau sejenis Logika Matematika Kayu yang ditujukan untuk anak usia prasekolah.', 0.0, 0),
	(53, 'Balok Abjad & Angka Kayu', 'Edukasi', NULL, 40000, 19, 'Edukasi 4.jpeg', 'Produk ini adalah satu set balok-balok kayu kubus yang dicetak dengan berbagai karakter edukatif seperti huruf (abjad), angka, dan gambar/simbol sederhana. Balok-balok ini adalah mainan klasik yang sangat serbaguna untuk anak usia dini.', 0.0, 0),
	(54, 'Set Bowling Mini Warna-warni', 'Edukasi', NULL, 30000, 11, 'Edukasi 5.jpeg', 'Produk ini adalah set mainan bowling mini yang terbuat dari bahan kayu, dirancang khusus untuk permainan anak-anak dan tujuan edukasi. Dapat digunakan untuk mengajarkan konsep berhitung dan penjumlahan/pengurangan sederhana (misalnya, menghitung berapa pin yang jatuh). ', 0.0, 0),
	(55, 'Mainan Telepon Interaktif VTech Disney Winnie the Pooh', 'Edukasi', NULL, 80000, 10, 'Edukasi 6.jpeg', 'Produk ini adalah telepon mainan interaktif dan edukatif bermerek VTech dengan tema karakter Disney populer, Winnie the Pooh dan Tigger.', 0.0, 0),
	(56, 'Action Figure Donquixote Rosinante / Corazon', 'Action Figure', NULL, 700000, 2, 'Robot 12.jpeg', 'Produk ini adalah figur aksi atau patung koleksi (biasanya dari PVC) yang menggambarkan karakter populer dari serial anime dan manga One Piece. Karakter yang digambarkan adalah Corazon (nama asli: Donquixote Rosinante), dalam penampilannya yang mengenakan jubah bulu berwarna gelap.', 0.0, 0),
	(57, 'Action Figur Tony Tony Chopper', 'Action Figure', NULL, 350000, 13, 'Robot 13.jpeg', 'Figur ini adalah gambaran dari karakter Tony Tony Chopper dari One Piece dalam transformasinya yang paling kuat, yaitu Monster Point. Chopper ditampilkan dalam wujud monster rusa yang besar, dengan bulu cokelat lebat, tanduk besar, dan ekspresi wajah yang berteriak. Ia mengenakan celana pendek biru dan topi khasnya yang berwarna biru-merah muda.', 0.0, 0),
	(58, 'Action Figure Izuku Midoriya - Deku', 'Action Figure', NULL, 900000, 3, 'Robot 16.jpeg', 'Figur aksi Izuku Midoriya ("Deku") dari My Hero Academia dalam kostum hero terbarunya, dengan jubah kuning/cokelat yang melilit leher dan lengan serta kaki yang diperkuat.', 0.0, 0),
	(59, 'Action Figure Katsuki Bakugo', 'Action Figure', NULL, 900000, 2, 'Robot 17.jpeg', 'Figur aksi Katsuki Bakugo dari My Hero Academia dalam kostum pahlawannya yang khas, berwarna hitam dan oranye, dengan pelindung tangan besar dan ekspresi agresif.', 0.0, 0),
	(60, 'Action Figure Toji Fushiguro', 'Action Figure', NULL, 950000, 4, 'Robot 18.jpeg', 'Figur patung Toji Fushiguro. Ia digambarkan mengenakan kaus hitam lengan pendek yang menampilkan fisik berototnya dan celana hakama lebar berwarna abu-abu/biru muda. Figur berdiri di atas alas batu.', 0.0, 0),
	(61, 'Action Figure Vision', 'Action Figure', NULL, 800000, 11, 'Robot 19.jpeg', 'Figur aksi atau patung Vision, karakter Marvel, dalam kostum superhero berwarna hijau tua, merah maroon, dan emas. Wajahnya berwarna merah, dengan detail kepala android dan jubah emas yang terentang. Pose sedang melayang.', 0.0, 0),
	(62, 'Action Figure Koba', 'Action Figure', NULL, 700000, 14, 'Robot 20.jpeg', 'Figur aksi atau patung Koba, kera prajurit dari film Planet of the Apes. Figur ini berbulu cokelat tua, ekspresi mengaum, dan memegang senapan.', 0.0, 0),
	(63, 'Boneka Bebek Kuning', 'Boneka', NULL, 100000, 12, 'Boneka 10.jpeg', 'Boneka plush berbentuk anak bebek berwarna kuning cerah dengan paruh oranye dan mata hitam. Memakai dasi kupu-kupu merah dengan motif polkadot putih.', 0.0, 0),
	(64, 'Boneka Tom ', 'Boneka', NULL, 180000, 9, 'boneka 11.jpeg', 'Boneka plush karakter Tom, kucing abu-abu dari kartun Tom and Jerry. Memiliki mata hijau besar dan telapak tangan/kaki berwarna putih.', 0.0, 0),
	(65, 'Boneka Jerry', 'Boneka', NULL, 180000, 8, 'boneka12.jpeg', 'Boneka plush karakter Jerry, tikus cokelat dari kartun Tom and Jerry. Memiliki telinga besar berwarna pink dan ekor kecil.', 0.0, 0),
	(66, 'Lotso Huggin  Bear', 'Boneka', NULL, 200000, 5, '06012026195624lotso.jpg', 'Boneka plush karakter Lotso dari film Toy Story. Beruang berwarna pink cerah dengan hidung ungu dan krem. ', 0.0, 0),
	(70, 'Hot Wheels - Lamborghini Huracán LP 620-2 Super Trofeo', 'Kendaraan', NULL, 40000, 11, 'mobil 5.jpeg', 'Mobil diecast Hot Wheels model Lamborghini Huracán LP 620-2 Super Trofeo berwarna abu-abu metalik/hitam. Edisi tahun 2016.', 0.0, 0),
	(76, 'Mobil Pagani Zonda', 'Kendaraan', NULL, 30000, 19, '08122025135907Mobil 1.jpeg', 'Mobil mainan (kemungkinan bukan diecast koleksi) model supercar (mirip Pagani Zonda) berwarna ungu metalik cerah. Memiliki fitur buka-tutup pintu.', 0.0, 0),
	(77, 'Mobil Balap GT ', 'Kendaraan', NULL, 30000, 8, '08122025140133Mobil 2.jpeg', 'Mobil mainan diecast atau plastik model mobil balap GT (Racing Car) yang dimodifikasi ekstrem, berwarna merah dan kuning/hijau neon, dengan banyak stiker/dekorasi.', 0.0, 0),
	(78, 'Action Figure Denji ', 'Action Figure', NULL, 800000, 12, '11122025094435denji.jpeg', 'Figur Denji dalam transformasi Chainsaw Man yang menampilkan kepala gergaji, serta gergaji di kedua lengannya. Ia mengenakan kemeja, dasi, dan celana gelap yang robek akibat transformasi. Posenya rendah dan siap menerjang. Figur ini memiliki base bundar sederhana.', 0.0, 0),
	(79, 'Action Figure Makima', 'Action Figure', NULL, 800000, 4, '11122025094552Makima.jpeg', 'Figur Makima ini menangkap penampilannya sebagai Pemburu Iblis Keamanan Publik, mengenakan kemeja putih, dasi hitam, dan celana kulit hitam. Posenya tegas dengan kedua tangan terlipat di depan dada. Figur ini memiliki base berupa puing-puing, yang menambah feel dramatis dari seri tersebut.', 0.0, 0),
	(80, 'Action Figure Power', 'Action Figure', NULL, 750000, 12, '06012026194039power.jpg', 'Figur Power, Iblis Darah, dalam seragam Pemburu Iblisnya yang longgar. Posenya dinamis dan agresif, menunjukkan taring dan tanduknya yang menonjol, dengan tangan terentang seolah akan menyerang. Jaketnya tersampir di bahu, dan sepatunya memiliki detail warna merah muda.', 0.0, 0),
	(81, 'Action Figure Zero Two', 'Action Figure', NULL, 500000, 2, '11122025094817Zero Two.jpeg', 'Figur ini menampilkan Zero Two dalam Plugsuit merah khasnya yang mengkilap, dengan rambut merah muda ikoniknya. Posenya tegak dengan tangan di pinggul atau di samping. Detail pada Plugsuit dan rambut tampak cukup baik untuk figur prize atau figur non-skala.', 0.0, 0),
	(82, 'Boneka Hatsune', 'Boneka', NULL, 200000, 12, '11122025100201Boneka Hatsune.jpeg', 'Boneka plush dengan gaya Chibi atau chimi-chara. Menampilkan rambut kuncir dua (pigtails) biru-hijau khasnya, seragam standar, dan headphone. Boneka ini memiliki ekspresi wajah yang imut.', 0.0, 0),
	(83, 'Boneka Doraemon', 'Boneka', NULL, 100000, 40, '11122025100723Doraemon.jpeg', 'Boneka plush Doraemon, robot kucing ikonik berwarna biru. Ciri khasnya adalah mata besar, hidung merah, kumis, dan kalung dengan lonceng kuning di lehernya. Posenya duduk standar.', 0.0, 0),
	(84, 'Boneka Jax plush', 'Boneka', NULL, 70000, 20, '11122025100831Jax plush.jpeg', 'Boneka plush karakter Jax, kelinci ungu tinggi dengan overalls merah muda dan sarung tangan kuning. Boneka ini menampilkan mata hitam besar dengan celah dan senyum lebar yang khas.', 0.0, 0),
	(85, 'Boneka Minion', 'Boneka', NULL, 250000, 21, '11122025100907Minion.jpeg', 'Boneka plush Minion kuning dengan goggles (kacamata) dan overall jeans biru. Karakter ini terlihat memegang boneka beruang kecil berwarna cokelat, kemungkinan besar adalah Minion "Bob" yang memegang beruang "Tim" atau boneka Tim dengan ukuran lebih besar.', 0.0, 0),
	(86, 'Boneka Pochita', 'Boneka', NULL, 300000, 15, '11122025100952Pochita.jpeg', 'Boneka plush Pochita berwarna oranye cerah, Iblis Gergaji. Ciri khasnya adalah mata bulat, senyum lebar, dan gergaji mesin yang menjadi kepala dan gagangnya sebagai pegangan di punggungnya. Boneka ini memiliki bentuk imut yang umum untuk produk plush karakter ini.', 0.0, 0),
	(88, 'Tomica No. 6 Audi R8', 'Kendaraan', NULL, 150000, 25, '11122025102015mobil 7.jpeg', 'Mobil miniatur die-cast merek Tomica (Takara Tomy). Modelnya adalah Audi R8 berwarna hitam, dengan skala 1/62. Tomica dikenal karena kualitas dan suspensi mainannya. Dijual dalam kemasan kotak standar.', 0.0, 0),
	(89, 'Set Mobil Die-Cast Campuran', 'Kendaraan', NULL, 150000, 18, '11122025102207download (6).jpeg', 'Set berisi 6 buah mobil miniatur die-cast dengan skala yang diperkirakan 1:64 atau sejenisnya. Modelnya beragam, mencakup SUV/Jip (hijau, kuning, hitam), pick-up (biru), dan mobil sport (merah, kuning, hitam, hijau). Seringkali memiliki fitur pintu yang dapat dibuka.', 0.0, 0),
	(90, 'Hot Wheels 19 Corvette ZR1 Convertible', 'Kendaraan', NULL, 50000, 21, '11122025110135corvette zr 1.jpeg', 'Mobil miniatur Hot Wheels edisi 2020 Mainline, warna biru, bagian dari seri Factory Fresh (2/10). Model berdasarkan Chevrolet Corvette ZR1 Convertible tahun 2019.', 0.0, 0),
	(91, 'Hot Wheels 2020 Ford Mustang Shelby GT500', 'Kendaraan', NULL, 50000, 14, '11122025110244Mustang.jpeg', 'Mobil miniatur Hot Wheels edisi 2020 Mainline, warna biru dengan garis putih (striping), bagian dari seri Muscle Mania (1/10). Model berdasarkan Ford Mustang Shelby GT500 tahun 2020.', 0.0, 0),
	(92, 'Hot Wheels Porsche 911 GT3 RS', 'Kendaraan', NULL, 50000, 13, '11122025110331Porsche.jpeg', 'Mobil miniatur Hot Wheels edisi 2020 Mainline, warna ungu metalik, bagian dari seri Factory Fresh (10/10). Model berdasarkan Porsche 911 GT3 RS.', 0.0, 0),
	(93, 'Kids ATV Large 24v Electric Ride-on Buggy with MP4 TV,', 'Kendaraan', NULL, 8500000, 5, '11122025111125mobil merah.jpeg', 'Mobil Mainan Listrik Anak (Ride-on UTV/Buggy) ini menampilkan desain off-road yang sporty dan tangguh, menonjol dengan kombinasi warna merah pada bodi utama dan aksen biru cerah pada roda besar, kursi, dan detail trim. Sebagai model dua penumpang, ia memberikan pengalaman berkendara yang realistis bagi anak-anak dengan fitur-fitur seperti lampu LED, sabuk pengaman, dan kontrol setir. Produk ini umumnya ditenagai oleh baterai isi ulang (seringkali 12V atau 24V) dan, seperti kebanyakan mainan sejenis, mungkin dilengkapi dengan Remote Control Orang Tua untuk keselamatan dan fitur hiburan tambahan seperti konektivitas musik.', 0.0, 0),
	(94, 'Mobil Polisi Transformer RC', 'Kendaraan', NULL, 300000, 11, '11122025114329gambar 21.jpeg', 'Ini adalah mainan yang dapat berubah bentuk (transformer) yang dikendalikan dari jarak jauh (Remote Control / RC). Mainan ini menampilkan dua mode:\r\n1. Mode Kendaraan: Berbentuk mobil sport futuristik berwarna hitam yang menyerupai mobil polisi, lengkap dengan lampu sirene LED merah dan biru yang menyala.\r\n\r\n2. Mode Robot: Berubah menjadi robot action figure dominan hitam dengan aksen biru metalik dan silver, siap beraksi.', 0.0, 0),
	(95, 'Mobil Listrik Anak SUV', 'Kendaraan', NULL, 7000000, 21, '11122025114519gambar 22.jpeg', 'obil Listrik Anak SUV (G-Class Look): Mobil ride-on bertenaga aki anak-anak berwarna hitam yang meniru desain Mercedes-Benz G-Class/AMG.', 0.0, 0),
	(96, 'Mobil Listrik Anak Chevrolet Camaro', 'Kendaraan', NULL, 5500000, 12, '11122025114638kids car.jpeg', 'Mobil ride-on bertenaga aki, dua penumpang, berwarna hitam dengan stripe putih, meniru model Camaro Convertible.', 0.0, 0),
	(97, 'Set Mainan Konstruksi', 'Kendaraan', NULL, 150000, 30, '11122025114813Mobil Mobilan.jpeg', 'Set 6-in-1 kendaraan alat berat/konstruksi (Loader, Dump Truck, Excavator, dll.) dominan warna kuning. Cocok untuk balita.', 0.0, 0),
	(98, 'Little Tikes Cozy Coupe', 'Kendaraan', '6+ Tahun', 1500000, 2, '11122025115312mobil 23.jpeg', 'Mobil dorong balita ikonik (kaki) berwarna merah dengan atap kuning. Dikenal karena daya tahannya.', 0.0, 0),
	(99, 'Truk Molen Mercedes-Benz Actros', 'Kendaraan', '6+ Tahun', 450000, 3, '11122025115355Mobil 24.jpeg', 'Diecast truk pengaduk semen, kabin biru, molen kuning-biru. Model skala detail.', 0.0, 0),
	(100, 'Geometric Stacker', 'Edukasi', '6+ Tahun', 50000, 15, '12122025063046edukasi 1.jpeg', 'Mainan ini adalah Geometric Stacker yang dirancang estetis dengan palet warna pastel yang lembut (biru muda, hijau mint, oranye muda, dan pink/ungu). Terbuat dari kayu, mainan ini terdiri dari papan dasar, serangkaian tiang pasak yang tersusun dalam kelompok, dan berbagai blok geometri seperti persegi, segitiga, segi lima, dan lingkaran.\r\n\r\nSetiap blok bentuk memiliki jumlah lubang yang berbeda dan harus dicocokkan (disortir dan ditumpuk) dengan kelompok tiang pasak yang sesuai di papan dasar. Mainan ini berfungsi ganda untuk melatih keterampilan motorik halus, pengenalan bentuk dan warna, serta membantu pemahaman awal anak mengenai konsep jumlah dan pemecahan masalah saat mencoba menumpuk blok dengan benar.', 0.0, 0),
	(101, 'Balok Susun Jumbo Warna-Warni', 'Edukasi', '6+ Tahun', 100000, 8, '12122025064932edukasi2.jpeg', 'Set mainan ini adalah Balok Susun Plastik berukuran besar (jumbo/Duplo-style), dirancang khusus agar mudah dimainkan oleh anak usia dini. Menggunakan warna-warna dasar dan cerah (merah, biru, kuning, hijau), balok-balok ini memiliki sistem saling mengunci (interlocking) yang memungkinkan anak membangun berbagai macam kreasi, mulai dari model realistis seperti rumah, helikopter, jerapah, dan gajah, hingga bentuk edukatif seperti angka (1, 2, 3). Mainan ini merupakan alat yang sangat efektif untuk melatih keterampilan motorik halus, merangsang kreativitas dan imajinasi, serta mengajarkan dasar-dasar pengenalan warna, bentuk, dan konsep ruang kepada anak.', 0.0, 0),
	(102, 'Mainan Laptop Belajar Anak', 'Edukasi', '6+ Tahun', 50000, 20, '12122025065743edukasi 3.jpeg', 'Mainan ini adalah perangkat edukasi elektronik berbentuk laptop mini lipat yang ringan dan portabel. Mainan ini ditujukan untuk anak usia pra-sekolah, menampilkan desain menarik dengan karakter-karakter populer (seperti tema Ice Kingdom/Frozen), tersedia dalam berbagai warna cerah seperti merah, ungu, pink, dan biru.\r\n\r\nPerangkat ini berfungsi sebagai alat bantu belajar dengan tombol-tombol yang besar dan mudah dioperasikan, meliputi tombol angka (1-10) dan tombol huruf abjad. Dengan fitur suara interaktif, mainan ini membantu anak dalam pengenalan abjad dan angka, melatih keterampilan pra-membaca, serta mengembangkan koordinasi tangan-mata melalui pembelajaran yang menyenangkan dan musik.', 0.0, 0),
	(103, 'Mainan Cincin Susun', 'Edukasi', '3+ Tahun', 35000, 11, '12122025070420edukasi4.jpeg', 'Set mainan ini adalah mainan klasik Cincin Susun (Stacking Rings) yang terbuat dari plastik dan ditujukan untuk bayi dan balita. Mainan ini terdiri dari tiang kerucut dan serangkaian cincin berwarna pelangi yang cerah (merah, oranye, kuning, hijau, biru, ungu) dengan ukuran bertingkat. Anak harus menumpuk cincin-cincin tersebut ke tiang sesuai urutan ukurannya, dari yang terbesar di bawah hingga yang terkecil di atas.\r\n\r\nSet ini juga dilengkapi dengan satu bebek karet kuning yang sering digunakan sebagai teman bermain di air atau di kamar mandi. Mainan ini sangat baik untuk melatih keterampilan motorik halus, mengenalkan konsep ukuran (besar-kecil) dan urutan, serta membantu pengenalan warna pada anak.', 0.0, 0),
	(104, 'Papan Congklak', 'Edukasi', '6+ Tahun', 30000, 5, '12122025070606edukasi 5.jpeg', 'Mainan ini adalah papan permainan tradisional Congklak atau Dakon yang terbuat dari plastik yang ringan, dan tersedia dalam warna-warna cerah seperti merah, hijau, dan biru. Papan ini memiliki bentuk lonjong, menampilkan dua baris lubang kecil (masing-masing 7 lubang) serta dua lubang besar di ujung (lumbung). Set ini biasanya sudah dilengkapi dengan biji congklak.', 0.0, 0),
	(105, 'Mainan Alat Musik Marakas Kayu', 'Edukasi', '3+ Tahun', 50000, 43, '12122025070909edukasi6.jpeg', 'Mainan ini adalah sepasang alat musik perkusi sederhana berupa Marakas yang terbuat dari kayu dengan pegangan yang kokoh. Kepala marakas berbentuk oval diisi dengan material yang menghasilkan suara gemerincing saat digoyangkan, menjadikannya alat yang ideal untuk mengenalkan musik dan ritme pada anak.\r\n\r\nKedua marakas memiliki desain yang menarik dan berbeda: satu dicat dengan garis-garis pelangi cerah (merah, hijau, kuning, biru), dan yang lainnya berwarna biru solid dengan titik-titik (polkadot). Mainan ini sangat baik untuk melatih keterampilan motorik kasar anak (menggenggam dan mengayun) serta mengembangkan sensori dan rasa irama.', 0.0, 0),
	(106, 'Xylophone ( Piano Mini )', 'Edukasi', '3+ Tahun', 90000, 50, '12122025071921edukasi8.jpeg', 'Ini adalah mainan musik mini yang tampaknya diproduksi oleh merek Little Tikes. Desainnya berbentuk hati/cangkang merah dengan empat bilah berwarna cerah (oranye, kuning, hijau, biru) yang berfungsi sebagai bilah xylophone (dipukul) dan empat tombol berwarna serupa di bagian bawah yang berfungsi sebagai piano/keyboard (ditekan). Mainan ini menggabungkan dua cara bermain musik dalam satu perangkat.', 0.0, 0),
	(107, 'Drum Mainan Anak', 'Edukasi', '3+ Tahun', 50000, 21, '12122025072024edukasi7.jpeg', 'Mainan ini adalah Drum Mainan silinder dengan tali gantung. Badan drum dihiasi dengan ilustrasi karakter kartun yang berwarna-warni (tampaknya bertema "Bob Zoom"). Drum ini dilengkapi dengan dua stik/pemukul kuning.', 0.0, 0),
	(108, 'Pistol Air Ransel Doraemon', 'Edukasi', '6+ Tahun', 65000, 13, '12122025072108edukasi9.jpeg', 'Ini adalah mainan Pistol Air yang unik. Tangki airnya berbentuk karakter kartun Doraemon dan dapat dikenakan sebagai ransel (dilengkapi tali bahu). Pompa pistol terhubung ke tangki ransel melalui selang, memungkinkan anak bermain air dalam jangka waktu lama tanpa perlu sering mengisi ulang.', 0.0, 0);

-- Dumping structure for table db_tokomainan.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nama` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `no_hp` varchar(20) DEFAULT NULL,
  `alamat` text,
  `data_keranjang` text,
  `foto` varchar(255) DEFAULT 'default.png',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table db_tokomainan.users: ~0 rows (approximately)

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
